### ISSUE TITLE
MIUI10权限都开后，还是无法打开

### ISSUE THREAD

**Issue by HakunamatataLeo** [Nevolution/sdk#16]

**Comment by notxx** [comment]
自启动要打开，然后省电策略必须设置为无限制。如果有相关插件，比如“微信通知·现代简约风”也要设置成一样的。但是这样也智能做到每次安装完了以后可以打开，只要重启就完了。

**Comment by oasisfeng** [comment]
请确认 v3.0.4 是否已解决上述问题？
