### ISSUE TITLE
MIUI每次重启都没法启动nevo，必须卸载重装

### ISSUE THREAD

**Issue by notxx** [Nevolution/sdk#18]
最近特意抓了一遍logcat，似乎是这里

```
01-18 17:05:04.732  2535  2799 E adTracker: Value Nevo.NUI of type java.lang.String cannot be converted to JSONObject
01-18 17:05:04.733  2535  2799 E adTracker: Value Nevo.NUI|AppBgSettings of type java.lang.String cannot be converted to JSONObject
```

**Comment by notxx** [comment]
将“女娲石·通知进化”更新到了3.0.4，“Nevo - 微信·当代通知体验”更新到了2.1，重启手机，还是不能正确启动。抓了一次logcat，似乎变成这样了
```
01-28 21:47:36.214  1932  2183 E adTracker: Value Nevo.NUI of type java.lang.String cannot be converted to JSONObject
01-28 21:47:36.214  1932  2183 E adTracker: Value Nevo.NUI|AppBgSettings of type java.lang.String cannot be converted to JSONObject
01-28 21:47:37.059  1932  1932 E adTracker: Value Nevo.NUI|AppBgSettings of type java.lang.String cannot be converted to JSONObject
```

**Comment by oasisfeng** [comment]
Fixed in v3.0.4.

**Comment by oasisfeng** [comment]
> 将“女娲石·通知进化”更新到了3.0.4，“Nevo - 微信·当代通知体验”更新到了2.1，重启手机，还是不能正确启动。抓了一次logcat，似乎变成这样了
> 
> ```
> 01-28 21:47:36.214  1932  2183 E adTracker: Value Nevo.NUI of type java.lang.String cannot be converted to JSONObject
> 01-28 21:47:36.214  1932  2183 E adTracker: Value Nevo.NUI|AppBgSettings of type java.lang.String cannot be converted to JSONObject
> 01-28 21:47:37.059  1932  1932 E adTracker: Value Nevo.NUI|AppBgSettings of type java.lang.String cannot be converted to JSONObject
> ```

以上日志与此问题无关，烦请在（出现问题的）重启后抓取完整的日志，或者生成错误报告（系统设置 - 开发者选项中）

**Comment by notxx** [comment]
用USB调试然后logcat抓不到别的Nevo相关日志了。马上来重启“生成错误报告”试一下。要上传什么文件？生成错误报告这个功能我不太熟

**Comment by notxx** [comment]
MIUI真是太魔改了，开发者选项没有“生成错误报告”😂。按照[MIUI官方方式](https://dev.mi.com/doc/p=1452/index.html)生成了一个MIUI格式的错误报告，里面解开好像有个文件是原生的错误报告😂。请见附件。
[bugreport-polaris-PKQ1.180729.001-2019-02-03-16-51-57.zip](https://github.com/Nevolution/sdk/files/2825339/bugreport-polaris-PKQ1.180729.001-2019-02-03-16-51-57.zip)

**Comment by oasisfeng** [comment]
从日志看，MIUI 的自启动控制屏蔽了 Nevolution 的启动流程，需要修改系统设置，为 Nevolution 允许自启动。（参见 https://nevo.app/compatibility ）

**Comment by notxx** [comment]
目前已经没在用MIUI，不过之前用的时候会遇到在应用智能省电-nevo里面，每次重启配置都会从“无限制”跳成“智能省电”的情况，所以大概还是MIUI的锅吧。

**Comment by notxx** [comment]
最近重回MIUI，试了一下使用magisk里面的app systemizer来把nevo变成系统模块，重启之后的自启动已经OK。
