### ISSUE TITLE
微信新消息没有声音和震动

### ISSUE THREAD

**Issue by ddggh5566** [Nevolution/sdk#19]
微信来新消息时没有声音和震动
小米6
Android 8.0
MIUI 10.0.1.0 | 稳定版
微信版本：play版7.0.0
Nevo 3.0.2
工作模式：insider
未开启高级模式（执行命令报错）
未安装Extension Pack

其它信息：
微信和Nevo，Nevo-Wechat的通知都打开了。
看酷安说很多人升级到微信7.0后都出现了没有声音的情况，具体情况未知（荣耀v10，华为Mate 20 Pro，三星Galaxy S9+，一加3T）
未使用此软件时微信只有震动没有声音，已知另一位小米6用户也有此问题。
微信更新到7.0后，声音与震动的设置发生了变化（如图）
另一部手机红米Note 4x，Android 7.0，miui10，微信play7.0，微信的声音和震动设置未发生变化，Nevo有声音和震动。
![screenshot_2019-01-23-09-27-46-239_com tencent mm](https://user-images.githubusercontent.com/17005920/51577566-3c5c1800-1ef5-11e9-87d6-306afdfd0555.png)

**Comment by ysc3839** [comment]
可能是 MIUI 的问题，MIUI 设置中去掉了 Android O 选择通知铃声的选项。
可以使用 [AutoNotification](https://play.google.com/store/apps/details?id=com.joaomgcd.autonotification) 修改通知设置。

**Comment by oasisfeng** [comment]
微信插件相关的问题反馈，请提交至 https://github.com/Nevolution/decorator-wechat/issues
